// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gpprdjdeydavukbufibf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdwcHJkamRleWRhdnVrYnVmaWJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI4MDM1MjIsImV4cCI6MjA3ODM3OTUyMn0.GYchsBaDQLHRCdM9wPepOih-KkntYjTcN5s-NZZ5i8c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});